### ISSUE TITLE
Voice Commands

### ISSUE THREAD

**Issue by gannonprudhomme** [gannonprudhomme/Desktop-Control-Tablet#20]
Add a microphone, then use a speech-to-text service to run commands, or use Amazon Alexa or Google Assistant

**Comment by FrozenAtlas** [comment]
unless there is a good api or engine for it i dont think we would be able to do this easily

**Comment by gannonprudhomme** [comment]
There are plenty of possible ways we could implement it, Google Voice API, Amazon has a set up for turning a Pi into an Echo, I think Google has another implementation for it as well that's related to their Google Home Assistant thing

Likewise, there are 3 "major" community made speech-to-text libraries/frameworks we could use.

Lastly, could implement it with a standalone amazon echo using the Amazon API, although idk if you have one

**Comment by FrozenAtlas** [comment]
about to make me buy a mic for the pi lmao
